---
- name: install ftp server on non prod servers
  hosts: centos
  become: yes
  tasks:
  - name: install vsftpd
    yum:
      name: vsftpd
    when: 
    - ansible_facts['distribution'] == "CentOs"
    - stage != "prod" 
